---

- name: Fail if required ihatemoney settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - ihatemoney_identifier
    - ihatemoney_uid
    - ihatemoney_gid
    - ihatemoney_hostname
    - ihatemoney_path_prefix
    - ihatemoney_container_network
    - ihatemoney_environment_variable_secret

- when: ihatemoney_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required ihatemoney Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - ihatemoney_container_labels_traefik_hostname
        - ihatemoney_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `ihatemoney_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if ihatemoney_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          ihatemoney_container_labels_traefik_path_prefix (`{{ ihatemoney_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/ihatemoney`).
      when: "ihatemoney_container_labels_traefik_path_prefix != '/' and ihatemoney_container_labels_traefik_path_prefix[-1] == '/'"
